version: "3"

services :
    node_backend:
        container_name: "node_backend"
        build: ./node_backend/
        ports:
         - '3001:3001'
    pg:
      image: "postgres"
      container_name: "postgres_container1"
      ports:
          - "4322:5432"
      environment:
         POSTGRES_PASSWORD: 'Password10'
         POSTGRES_USER: 'admin'
         POSTGRES_DB: 'testdata'    
      volumes:
          - ./pg/db_data:/var/lib/postgresql/data 

          





